name: Build
on: push

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check

  build-linux:
    runs-on: ubuntu-latest
    needs: flake-check
    strategy:
      matrix:
        host: [nixos, ci-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  build-darwin:
    runs-on: macos-latest
    needs: flake-check
    strategy:
      matrix:
        host: [my-macbook, ci-darwin]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel
